jenkins:
  systemMessage: "Jenkins configured automatically with JCasC 😎"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD:-admin123}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: "github-ssh-key"
              username: "git"
              description: "GitHub SSH Deploy Key"
              privateKeySource:
                directEntry:
                  privateKey: "${GITHUB_SSH_PRIVATE_KEY}"
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub-credentials"
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_PASSWORD}"
              description: "Docker Hub Credentials"

unclassified:
  location:
    url: "${JENKINS_URL:-http://localhost:8080/}"

tool:
  jdk:
    installations:
      - name: "JDK17"
        home: "/opt/java/openjdk"
  maven:
    installations:
      - name: "Maven-3.9"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"
  git:
    installations:
      - name: "Default"
        home: "git"

jobs:
  # --- CI Pipeline ---
  - script: >
      pipelineJob('java-app-ci') {
        description('CI pipeline: build, test, and push image')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:Amit-Shahal/jenkins-pipeline-task.git')
                  credentials('github-ssh-key')
                }
                branches('main')
              }
            }
            scriptPath('jenkins/jenkinsfile-ci')
          }
        }
        triggers {
          scm('H/5 * * * *')
        }
      }

  # --- CD Pipeline ---
  - script: >
      pipelineJob('java-app-cd') {
        description('CD pipeline: pull image and deploy locally')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('git@github.com:Amit-Shahal/jenkins-pipeline-task.git')
                  credentials('github-ssh-key')
                }
                branches('main')
              }
            }
            scriptPath('jenkins/jenkinsfile-cd')
          }
        }
      }

